# Generated by Django 4.2.30 on 2026-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет'),
        ),
    ]
