# Generated by Django 4.2.30 on 2026-05-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='icon',
        ),
    ]
